version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Zyr3xuser
      MYSQL_DATABASE: sales_report_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Zyr3xuser
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
