version: '3.8'

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=sales_report
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sales_report
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
