version: '3.8'

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Zyr3xuser  # Match with MySQL root password
      DB_NAME: sales_report_db # Match with MySQL database name
    ports:
      - "5000:5000"  # Map backend port
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      REACT_APP_BACKEND_URL: http://backend:5000
    ports:
      - "3000:3000"  # Expose frontend to the host
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sales_report
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"  # Map database port
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
