version: '3.8'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    depends_on:
      - backend
      - frontend
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"      # HTTP
      - "81:81"      # Admin Panel
      - "443:443"    # HTTPS

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Zyr3xuser
      - DB_NAME=sales_report_db
    expose:
      - "5000"       # Exposed internally for proxying
    depends_on:
      - db

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://backend:5000
    expose:
      - "3000"       # Exposed internally for proxying
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sales_report
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
