version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - database_network

networks:
  database_network:
    driver: bridge

volumes:
  db_data:

