version: '3.8'

services:
  nginx-proxy-manager-new:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager_new
    restart: always
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./nginx-new/data:/data
      - ./nginx-new/letsencrypt:/etc/letsencrypt
    ports:
      - "8082:80"      # HTTP remapped
      - "8083:81"      # Admin Panel remapped
      - "4444:443"     # HTTPS remapped


  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Zyr3xuser
      - DB_NAME=sales_report_db
    expose:
      - "5000"       # Exposed internally for proxying
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://backend:5000
    expose:
      - "3000"       # Exposed internally for proxying
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example  # Root password for MySQL
      MYSQL_DATABASE: sales_report  # Default database
    expose:
      - "3306"  # Only expose this port to the internal Docker network
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
