version: '3.8'
services:
  app:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    environment:
#      - CELERY_BROKER_URL=amqp://host.docker.internal:5672
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - /opt/NGINX_PM/data:/data
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - development

networks:
  development:
    name: development
    driver: bridge
